---
title: "p8105_hw5_fp2513"
output: github_document
date: "2024-11-07"
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(rvest)
```


## Problem 1

```{r}
birthday = sample(1:365, 10, replace = TRUE) %>% print()

if (any(duplicated(birthday))) {
  cat("TRUE")
} else {
  cat("FALSE")
}
```

```{r}
check_duplicate_birthdays = function(n) {  
  
  birthdays = sample(1:365, n, replace = TRUE)
 
    has_duplicates = any(duplicated(birthdays))

    return(has_duplicates)
   
}

n = 10
result = check_duplicate_birthdays(n)
cat("Do at least two people share a birthday?", result, n)

```

For each group size, compute the probability that at least two people in the group will share a birthday by averaging across the 10000 simulation runs. Make a plot showing the probability as a function of group size, and comment on your results.


```{r}
n_list = 2:50

output = vector("list", length = length(n_list))

for (i in seq_along(n_list)) {
  
  output[[i]] <- rerun(10000, check_duplicate_birthdays(n = n_list[i])) %>%
    unlist() %>%
    as.data.frame() %>%
    setNames(paste0("group_size_", n_list[i]))
}

birthday_result_df = bind_cols(output)
averages = colMeans(birthday_result_df)

average_birthday_dup_df = 
  data.frame(
  group_size = n_list,
  average = averages
)

```

```{r}

```

